### ISSUE TITLE
3.0.7: missing git tag?

### ISSUE THREAD

**Issue by kloczek** [jonbeebe/frontmatter#13]
According to https://pypi.org/project/frontmatter/ latest version is 3.0.7 however here there is no corresponding git tag.

**Comment by kloczek** [comment]
gentle ping .. 😋

**Comment by kloczek** [comment]
gentle ping .. again 🤔

**Comment by jonbeebe** [comment]
Apologies for the missing git tag. I just released 3.0.8 with associated git tag now.
