### ISSUE TITLE
pyyaml dependencies fixed to 5.3.1

### ISSUE THREAD

**Issue by cropr** [jonbeebe/frontmatter#18]
Frontmatter has a fixed dependency of pyyaml 5.3.1.  This version is more than 3 years old.  For a library as frontmatter, fixing a dependency is not ideal.   Pyyaml is currently is 6.0.1.  It would be better to put that that dependency  at minimal 5.3.1.

I am running a project which uses pyyaml 6.0.1 but this creates an issue when installing frontmatter

**Comment by kontur** [comment]
Same thing here, please bump the release requirements.

**Comment by jonbeebe** [comment]
Thanks for reporting this issue. I updated the Pipfile so that PyYAML dependency does not rely on a specific version and created a new release.

**Comment by moi90** [comment]
`PyYAML` is still pinned to 5.1 in `setup.py`:

https://github.com/jonbeebe/frontmatter/blob/63930c9925547da781f5f53625cf6935c01fa4fc/setup.py#L126
