### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by kylekirkby** [jonbeebe/frontmatter#7]
Hi @jonbeebe,

Looks like this module needs some dependency updates. Could you help bump the requirements?

ERROR: frontmatter 3.0.5 has requirement PyYAML==3.13, but you'll have pyyaml 5.1 which is incompatible.

Could we get this PR merged? 
https://github.com/jonbeebe/frontmatter/pull/5

Cheers,

Kyle

**Comment by jonbeebe** [comment]
@kylekirkby sure thing, I went ahead and merged it
